Repository WildCodeSchool/orleans-0218-taekwondo, pull requests merged in 2018-04, with the labels that each got.

#1 Base with firsts segmented files
  .gitignore
  app/db.php.dist
  app/routing.php
  public/assets/css/styles.css
  public/assets/plugins/bootstrap-3.3.7/css/bootstrap-theme.min.css
  public/assets/plugins/bootstrap-3.3.7/css/bootstrap.min.css
  public/assets/plugins/bootstrap-3.3.7/fonts/glyphicons-halflings-regular.eot
  public/assets/plugins/bootstrap-3.3.7/fonts/glyphicons-halflings-regular.svg
  public/assets/plugins/bootstrap-3.3.7/fonts/glyphicons-halflings-regular.ttf
  public/assets/plugins/bootstrap-3.3.7/fonts/glyphicons-halflings-regular.woff
  public/assets/plugins/bootstrap-3.3.7/fonts/glyphicons-halflings-regular.woff2
  public/assets/plugins/bootstrap-3.3.7/js/bootstrap.min.js
  public/assets/plugins/jquery-3.3.1/jquery.min.js
  simple-mvc.sql
  src/Controller/HomeController.php
  src/Controller/ItemController.php
  src/Model/Item.php
  src/Model/ItemManager.php
  src/View/Home/access.html.twig
  src/View/Home/events.html.twig
  src/View/Home/home.html.twig
  src/View/Home/index.html.twig
  src/View/Home/presentation.html.twig
  src/View/Item/_form.html.twig
  src/View/Item/add.html.twig
  src/View/Item/edit.html.twig
  src/View/Item/index.html.twig
  src/View/Item/show.html.twig
  src/View/_footer.html.twig
  src/View/_navbar.html.twig
  src/View/layout.html.twig
Labels: Reviewed by PO

#2 Make working base accessible to everyone
  .gitignore
  app/db.php.dist
  app/routing.php
  public/assets/css/styles.css
  public/assets/plugins/bootstrap-3.3.7/css/bootstrap-theme.min.css
  public/assets/plugins/bootstrap-3.3.7/css/bootstrap.min.css
  public/assets/plugins/bootstrap-3.3.7/fonts/glyphicons-halflings-regular.eot
  public/assets/plugins/bootstrap-3.3.7/fonts/glyphicons-halflings-regular.svg
  public/assets/plugins/bootstrap-3.3.7/fonts/glyphicons-halflings-regular.ttf
  public/assets/plugins/bootstrap-3.3.7/fonts/glyphicons-halflings-regular.woff
  public/assets/plugins/bootstrap-3.3.7/fonts/glyphicons-halflings-regular.woff2
  public/assets/plugins/bootstrap-3.3.7/js/bootstrap.min.js
  public/assets/plugins/jquery-3.3.1/jquery.min.js
  simple-mvc.sql
  src/Controller/HomeController.php
  src/Controller/ItemController.php
  src/Model/Item.php
  src/Model/ItemManager.php
  src/View/Home/access.html.twig
  src/View/Home/events.html.twig
  src/View/Home/home.html.twig
  src/View/Home/index.html.twig
  src/View/Home/presentation.html.twig
  src/View/Item/_form.html.twig
  src/View/Item/add.html.twig
  src/View/Item/edit.html.twig
  src/View/Item/index.html.twig
  src/View/Item/show.html.twig
  src/View/_footer.html.twig
  src/View/_navbar.html.twig
  src/View/layout.html.twig
Labels: Reviewed by PO

#3 S1 - Navigation Bar
  public/assets/css/styles.css
  src/View/_navbar.html.twig
Labels: Reviewed by PO

#4 S1 home events
  src/Controller/HomeController.php
  src/View/Home/events.html.twig
Labels: Reviewed by PO

#5 S1 description club
  app/db.php.dist
  public/assets/css/styles.css
  public/assets/images/trigrams/earth-h.png
  public/assets/images/trigrams/earth.png
  public/assets/images/trigrams/fire-h.png
  public/assets/images/trigrams/fire.png
  public/assets/images/trigrams/sky-h.png
  public/assets/images/trigrams/sky.png
  public/assets/images/trigrams/water-h.png
  public/assets/images/trigrams/water.png
  src/View/Home/presentation.html.twig
Labels: Reviewed by PO

#6 S1 description club
  src/View/Home/presentation.html.twig
Labels: Reviewed by PO

#8 picture for the presentation was missing
  public/assets/images/flyers.jpg
Labels: Reviewed by PO

#7 Create map and schedules table
  app/config.php
  app/db.php.dist
  public/assets/css/styles.css
  public/assets/js/home-map.js
  public/assets/plugins/leaflet/images/layers-2x.png
  public/assets/plugins/leaflet/images/layers.png
  public/assets/plugins/leaflet/images/marker-icon-2x.png
  public/assets/plugins/leaflet/images/marker-icon.png
  public/assets/plugins/leaflet/images/marker-shadow.png
  public/assets/plugins/leaflet/leaflet-src.js
  public/assets/plugins/leaflet/leaflet-src.js.map
  public/assets/plugins/leaflet/leaflet.css
  public/assets/plugins/leaflet/leaflet.js
  public/assets/plugins/leaflet/leaflet.js.map
  src/Controller/HomeController.php
  src/View/Home/access.html.twig
  src/View/Home/index.html.twig
Labels: Changement requested, Reviewed by PO

#11 Fix dev branch
  public/assets/css/styles.css
  src/Controller/HomeController.php
  src/View/Home/access.html.twig
  src/View/Home/events.html.twig
Labels: Reviewed by PO

#12 Dev to master #1
  app/config.php
  app/db.php.dist
  public/assets/css/styles.css
  public/assets/images/flyers.jpg
  public/assets/images/trigrams/earth-h.png
  public/assets/images/trigrams/earth.png
  public/assets/images/trigrams/fire-h.png
  public/assets/images/trigrams/fire.png
  public/assets/images/trigrams/sky-h.png
  public/assets/images/trigrams/sky.png
  public/assets/images/trigrams/water-h.png
  public/assets/images/trigrams/water.png
  public/assets/js/home-map.js
  public/assets/plugins/leaflet/images/layers-2x.png
  public/assets/plugins/leaflet/images/layers.png
  public/assets/plugins/leaflet/images/marker-icon-2x.png
  public/assets/plugins/leaflet/images/marker-icon.png
  public/assets/plugins/leaflet/images/marker-shadow.png
  public/assets/plugins/leaflet/leaflet-src.js
  public/assets/plugins/leaflet/leaflet-src.js.map
  public/assets/plugins/leaflet/leaflet.css
  public/assets/plugins/leaflet/leaflet.js
  public/assets/plugins/leaflet/leaflet.js.map
  src/Controller/HomeController.php
  src/View/Home/access.html.twig
  src/View/Home/events.html.twig
  src/View/Home/index.html.twig
  src/View/Home/presentation.html.twig
  src/View/_navbar.html.twig
Labels: Reviewed by PO

#13 S3 home event
  app/routing.php
  composer.lock
  db_schemes/event/mpd.mwb
  public/assets/images/event/TW1.jpg
  public/assets/images/event/TW2.jpg
  src/Controller/HomeController.php
  src/Model/Event/Event.php
  src/Model/Event/Manager.php
  src/View/Home/events.html.twig
Labels: Changement requested

#14 S3 Albums
  app/routing.php
  db_schemes/album/data.sql
  db_schemes/album/export.sql
  db_schemes/album/mpd.mwb
  db_schemes/album/mpd.mwb.bak
  public/assets/css/styles.css
  public/assets/js/app.js
  public/assets/plugins/featherlight-1.7.13/featherlight.min.css
  public/assets/plugins/featherlight-1.7.13/featherlight.min.js
  src/Controller/AlbumController.php
  src/Controller/HomeController.php
  src/Model/Album/Category.php
  src/Model/Album/Gallery.php
  src/Model/Album/Image.php
  src/Model/Album/Manager/Category.php
  src/Model/Album/Manager/Gallery.php
  src/Model/Album/Manager/Image.php
  src/View/Album/gallery.html.twig
  src/View/Album/index.html.twig
  src/View/_navbar.html.twig
  src/View/layout.html.twig
Labels: Reviewed by PO

#16 S3 event
  app/routing.php
  composer.json
  public/assets/css/styles.css
  src/Controller/EventController.php
  src/Model/Event/Manager.php
  src/View/Event/index.html.twig
  src/View/_navbar.html.twig
Labels: Reviewed by PO

#19 Fix navbar
  public/assets/css/styles.css
  public/assets/js/app.js
  src/View/_navbar.html.twig
Labels: Reviewed by PO

#17 Create home banner
  public/assets/css/styles.css
  public/assets/images/banners/stage.jpg
  src/View/Home/home.html.twig
Labels: Reviewed by PO

#20 Dev fixes s3
  app/db.php.dist
  app/routing.php
  db_schemes/event/data.sql
  db_schemes/event/export.sql
  public/assets/css/styles.css
  src/Controller/HomeController.php
  src/View/Event/index.html.twig
  src/View/Home/access.html.twig
  src/View/Home/events.html.twig
  src/View/Home/presentation.html.twig
  src/View/_navbar.html.twig
  src/View/layout.html.twig
Labels: Reviewed by PO

#24 S4 fix gallery presentation
  public/assets/css/styles.css
  src/Model/Album/Gallery.php
  src/Model/Album/Manager/Category.php
  src/Model/Album/Manager/Gallery.php
  src/Model/Album/Manager/Image.php
  src/View/Album/index.html.twig
Labels: Reviewed by PO

#26 Create the base of the administration
  app/routing.php
  public/assets/css/styles.css
  src/Controller/AdminController.php
  src/View/Admin/_navbar.html.twig
  src/View/Admin/index.html.twig
  src/View/Admin/layout.html.twig
Labels: Reviewed by PO

#31 Can delete a category
  app/routing.php
  public/assets/css/styles.css
  src/Controller/AlbumController.php
  src/Model/AbstractManager.php
  src/Model/Album/Manager/Category.php
  src/View/Album/Admin/Category/delete.html.twig
  src/View/Album/Admin/Category/index.html.twig
  src/View/Album/Admin/Category/list.html.twig
Labels: Reviewed by PO

#34 Can edit a category
  app/routing.php
  src/Controller/AlbumController.php
  src/Model/AbstractManager.php
  src/View/Album/Admin/Category/index.html.twig
  src/View/Album/Admin/Category/update.html.twig
Labels: Reviewed by PO

#30 S4 us26 event category filters
  app/db.php.dist
  src/Controller/EventController.php
  src/Model/Event/Manager.php
  src/View/Event/index.html.twig
Labels: Reviewed by PO

#35 Can create a gallery
  app/routing.php
  src/Controller/AlbumController.php
  src/View/Admin/_navbar.html.twig
  src/View/Album/Admin/Gallery/create.html.twig
  src/View/Album/Admin/Gallery/index.html.twig
Labels: Reviewed by PO

#36 Fix galleries search marge
  src/View/Album/index.html.twig
Labels: Reviewed by PO

#37 add data
  db_schemes/black_belt/data.sql
  db_schemes/black_belt/export.sql
Labels: Reviewed by PO

#39 Last fixes of the dev's branch
  app/db.php.dist
  app/routing.php
  blackBelt.sql
  bleckBelt_dump
  src/View/Album/Admin/Gallery/index.html.twig
  src/View/_navbar.html.twig
Labels: Reviewed by PO

#43 S5 fix forms confirmation
  public/assets/js/app.js
  src/View/Album/Admin/Category/delete.html.twig
Labels: Reviewed by PO

#48 Fix routes
  app/routing.php
  src/Controller/AlbumController.php
  src/View/Album/Admin/Category/delete.html.twig
  src/View/Album/Admin/Category/update.html.twig
Labels: Reviewed by PO

#49 S5_US19_Gallery_Delete
  app/routing.php
  src/Controller/AlbumController.php
  src/View/Album/Admin/Gallery/Update/delete.html.twig
  src/View/Album/Admin/Gallery/Update/index.html.twig
  src/View/Album/Admin/Gallery/Update/update.html.twig
Labels: Reviewed by PO

#51 View for the administrator : Event's part
  app/routing.php
  src/Controller/EventController.php
  src/Model/Event/Manager.php
  src/View/Admin/_navbar.html.twig
  src/View/Event/Admin/create.html.twig
  src/View/Event/Admin/index.html.twig
Labels: Reviewed by PO

#53 S5 us21 gallery photo add
  app/config.php
  app/routing.php
  src/Controller/AlbumController.php
  src/Model/Files/File.php
  src/Model/Files/Handler.php
  src/View/Album/Admin/Gallery/Update/images.html.twig
  src/View/Album/Admin/Gallery/Update/index.html.twig
  src/View/Album/Admin/Gallery/Update/upload.html.twig
Labels: Reviewed by PO

#55 Update db_schemes
  db_schemes/album/data.sql
  db_schemes/album/export.sql
  db_schemes/album/mpd.mwb.bak
  db_schemes/album/structure.sql
  db_schemes/black_belt/data.sql
  db_schemes/black_belt/structure.sql
  db_schemes/event/data.sql
  db_schemes/event/export.sql
  db_schemes/event/structure.sql
Labels: Reviewed by PO

#47 image's height and font-size modified
  db_schemes/black_belt/data.sql
  public/assets/css/styles.css
  public/assets/images/blackbelt/blackbelt.jpg
  src/Model/BlackBelt/BlackBelt.php
  src/View/BlackBelt/index.html.twig
  src/View/Home/access.html.twig
Labels: Reviewed by PO

#57 S5_US22_Gallery_Photo_Delete
  app/routing.php
  src/Controller/AlbumController.php
  src/Model/Album/Manager/Image.php
  src/View/Album/Admin/Gallery/Update/images.html.twig
Labels: Reviewed by PO

#61 Fix files upload
  src/Controller/AlbumController.php
Labels: Reviewed by PO

#62 Use sweetalert instead of window.confirm
  public/assets/js/app.js
  public/assets/plugins/sweetalert/sweetalert.min.js
  src/View/Admin/layout.html.twig
Labels: Reviewed by PO

#64 US32 Delete for Event's part
  app/routing.php
  src/Controller/EventController.php
  src/Model/Event/Manager.php
  src/View/Admin/_navbar.html.twig
  src/View/Event/Admin/create.html.twig
  src/View/Event/Admin/index.html.twig
Labels: Reviewed by PO

#66 presentation Taekwondo
  app/routing.php
  public/assets/css/styles.css
  public/assets/images/presentation/do.png
  public/assets/images/presentation/kwon.png
  public/assets/images/presentation/presentation_taekwondo.jpg
  public/assets/images/presentation/tae.png
  src/Controller/PresentationController.php
  src/View/Presentation/index.html.twig
  src/View/_navbar.html.twig
Labels: Reviewed by PO

#68 Fix gallery upload
  src/Controller/AlbumController.php
  src/Model/Files/File.php
Labels: Reviewed by PO

#73 S5 us57 01 formulaire
  public/assets/css/styles.css
  src/View/_footer.html.twig
Labels: Reviewed by PO

#77 Blackebelts list admin
  app/routing.php
  src/Controller/BlackBeltController.php
  src/Model/BlackBelt/Manager.php
  src/View/Admin/_navbar.html.twig
  src/View/BlackBelt/Admin/index.html.twig
Labels: Reviewed by PO

#78 Dev to master
  app/routing.php
  public/assets/css/styles.css
  src/Controller/AlbumController.php
  src/Controller/BlackBeltController.php
  src/Model/BlackBelt/Manager.php
  src/Model/Files/File.php
  src/View/Admin/_navbar.html.twig
  src/View/BlackBelt/Admin/index.html.twig
  src/View/_footer.html.twig
Labels: Reviewed by PO

#79 S5 us48 cn delete
  app/routing.php
  db_schemes/black_belt/data.sql
  db_schemes/black_belt/structure.sql
  src/Controller/BlackBeltController.php
  src/Model/BlackBelt/BlackBelt.php
  src/Model/BlackBelt/Manager.php
  src/View/Admin/_navbar.html.twig
  src/View/BlackBelt/Admin/index.html.twig
  src/View/BlackBelt/index.html.twig
Labels: Reviewed by PO

#74 S5 US30 event create // DB update
  app/config.php
  app/routing.php
  composer.json
  composer.lock
  db_schemes/event/data.sql
  public/assets/css/styles.css
  src/Controller/EventController.php
  src/Model/Album/Manager/Category.php
  src/Model/Event/Event.php
  src/Model/Event/Manager.php
  src/Model/Files/Handler.php
  src/View/Event/Admin/create.html.twig
  src/View/Event/Admin/index.html.twig
  src/View/Event/index.html.twig
  src/View/Home/events.html.twig
Labels: Reviewed by PO

#82 S5 us31 even edit + spelling mistakes
  app/routing.php
  publicassets/uploads/events/5ae0a67061233.png
  publicassets/uploads/events/5ae0a86b088a8.png
  publicassets/uploads/events/5ae0a8a9d8f79.png
  publicassets/uploads/events/5ae0a92e350cd.png
  src/Controller/EventController.php
  src/Model/AbstractManager.php
  src/View/Event/Admin/Update/index.html.twig
  src/View/Event/Admin/Update/update.html.twig
  src/View/Event/Admin/create.html.twig
  src/View/Event/Admin/index.html.twig
Labels: Reviewed by PO

#85 title's font-size and color o modification
  public/assets/css/styles.css
  src/View/Home/home.html.twig
Labels: Reviewed by PO

#87 Dev
  app/routing.php
  db_schemes/black_belt/data.sql
  db_schemes/black_belt/structure.sql
  public/assets/css/styles.css
  publicassets/uploads/events/5ae0a67061233.png
  publicassets/uploads/events/5ae0a86b088a8.png
  publicassets/uploads/events/5ae0a8a9d8f79.png
  publicassets/uploads/events/5ae0a92e350cd.png
  src/Controller/BlackBeltController.php
  src/Controller/EventController.php
  src/Model/AbstractManager.php
  src/Model/BlackBelt/BlackBelt.php
  src/View/BlackBelt/Admin/create.html.twig
  src/View/BlackBelt/Admin/index.html.twig
  src/View/Event/Admin/Update/index.html.twig
  src/View/Event/Admin/Update/update.html.twig
  src/View/Event/Admin/create.html.twig
  src/View/Event/Admin/index.html.twig
  src/View/Home/home.html.twig
Labels: Reviewed by PO

#93 S5 us39 office delete
  app/routing.php
  src/Controller/OfficeController.php
  src/View/Office/Admin/index.html.twig
Labels: Reviewed by PO

#96 S5 us40 office master view
  .gitignore
  public/assets/css/styles.css
  src/Controller/OfficeController.php
  src/Model/Office/Teacher/ManagerTeacher.php
  src/Model/Office/Teacher/Teacher.php
  src/View/Office/index.html.twig
Labels: Conflicts, Reviewed by PO

#95 S5 us58 formulaire
  app/db.php.dist
  app/routing.php
  public/assets/css/styles.css
  src/Controller/HomeController.php
  src/View/_footer.html.twig
  src/View/layout.html.twig
Labels: Reviewed by PO

#97 Dev
  .gitignore
  app/config.php
  app/db.php.dist
  app/routing.php
  public/assets/css/styles.css
  public/assets/images/event/TW1.jpg
  public/assets/images/event/TW2.jpg
  publicassets/uploads/events/5ae0a67061233.png
  publicassets/uploads/events/5ae0a86b088a8.png
  publicassets/uploads/events/5ae0a8a9d8f79.png
  publicassets/uploads/events/5ae0a92e350cd.png
  src/Controller/HomeController.php
  src/Controller/OfficeController.php
  src/Model/Office/Manager.php
  src/Model/Office/Office.php
  src/Model/Office/Teacher/ManagerTeacher.php
  src/Model/Office/Teacher/Teacher.php
  src/View/Admin/_navbar.html.twig
  src/View/Office/Admin/Update/index.html.twig
  src/View/Office/Admin/Update/update.html.twig
  src/View/Office/Admin/create.html.twig
  src/View/Office/Admin/index.html.twig
  src/View/Office/index.html.twig
  src/View/_footer.html.twig
  src/View/_navbar.html.twig
  src/View/layout.html.twig
Labels: Reviewed by PO

#98 S5 fixes master
  app/config.php
  public/assets/css/styles.css
  src/Controller/OfficeController.php
  src/View/Office/index.html.twig
Labels: Reviewed by PO

#99 section practice
  public/assets/css/styles.css
  public/assets/images/practice/casse.jpg
  public/assets/images/practice/combat.jpg
  public/assets/images/practice/competition.jpg
  public/assets/images/practice/defense.jpg
  public/assets/images/practice/kibon.jpg
  public/assets/images/practice/poomse.jpg
  src/Model/BlackBelt/BlackBelt.php
  src/View/Presentation/index.html.twig
Labels: Conflicts

#101 S5 us56 history
  app/config.php.dist
  app/db.php.dist
  public/assets/css/styles.css
  public/assets/images/blackbelt/south-korea.jpg
  public/assets/images/history/Lee_Master.png
  public/assets/images/history/Seal_of_the_Government-General_of_Korea.png
  public/assets/images/history/carte.PNG
  public/assets/images/history/korean_flag.jpg
  src/View/Presentation/index.html.twig
Labels: Changement requested
